carrier_codes = {
    'ABFS': 'ABF',
    'AWC': 'AllStatesWorld Cargo',
    'CNWY': 'XPO Logistics',
    'CTII': 'Central Transport',
    'DYLT': 'Daylight Trans',
    'EDXI': 'EDI Express',
    'EXLA': 'Estes Express',
    'FWDN': 'Forward Air',
    'FXFE': 'FedEx Freight',
    'FXNL': 'FedEx Freight',
    'HMES': 'USF Holland',
    'HRCF': 'Hercules',
    'KYSO': 'Keystone',
    'NPME': 'New Penn',
    'ODFL': 'Old Dominion',
    'PAAF': 'Pilot Freight',
    'PITT': 'Pitt Ohio',
    'PITD': 'Pitt Ohio',
    'PYLE': 'A. Duie Pyle',
    'RDWY': 'YRC',
    'RLCA': 'R&L Carriers',
    'SAIA': 'SAIA',
    'SEKO': 'Seko',
    'TAIF': 'Team Worldwide',
    'UPGF': 'UPS Freight',
    'UPS': 'UPS Ground',
    'WARD': 'Ward Trucking',
    'FEDG': 'Fedex Ground',
    'UPS2': 'UPS 2nd Day',
    'UPSN': 'UPS Next Day',
    'UPSG': 'UPS Ground',
    'FEDN': 'Fedex Next Day'
}
